### ISSUE TITLE
Error: Cannot find module 'gulp-tslint'

### ISSUE THREAD

**Issue by mcferren** [vladotesanovic/angular2-express-starter#1]
Tried to push the repo code as is to Heroku and was presented with this terminal error and heroku log error

error from terminal:

> ```
> Counting objects: 758, done.
> Delta compression using up to 8 threads.
> Compressing objects: 100% (549/549), done.
> Writing objects: 100% (758/758), 1.73 MiB | 43.00 KiB/s, done.
> Total 758 (delta 155), reused 758 (delta 155)
> remote: Compressing source files... done.
> remote: Building source:
> remote: 
> remote: -----> Node.js app detected
> remote: 
> remote: -----> Creating runtime environment
> remote:        
> remote:        NPM_CONFIG_LOGLEVEL=error
> remote:        NPM_CONFIG_PRODUCTION=true
> remote:        NODE_ENV=production
> remote:        NODE_MODULES_CACHE=true
> remote: 
> remote: -----> Installing binaries
> remote:        engines.node (package.json):  unspecified
> remote:        engines.npm (package.json):   unspecified (use default)
> remote:        
> remote:        Resolving node version (latest stable) via semver.io...
> remote:        Downloading and installing node 5.6.0...
> remote:        Using default npm version: 3.6.0
> remote: 
> remote: -----> Restoring cache
> remote:        Skipping cache restore (new runtime signature)
> remote: 
> remote: -----> Building dependencies
> remote:        Pruning any extraneous modules
> remote:        Installing node modules (package.json)
> remote:        
> remote:        > angular2-express-starter@1.0.0 postinstall /tmp/build_f65e1cd8c6973d691eef143f131c848c
> remote:        > gulp
> remote:        
> remote:        module.js:341
> remote:        throw err;
> remote:        ^
> remote:        
> remote:        Error: Cannot find module 'gulp-tslint'
> remote:        at Function.Module._resolveFilename (module.js:339:15)
> remote:        at Function.Module._load (module.js:290:25)
> remote:        at Module.require (module.js:367:17)
> remote:        at require (internal/module.js:16:19)
> remote:        at Object.<anonymous> (/tmp/build_f65e1cd8c6973d691eef143f131c848c/gulpfile.js:4:14)
> remote:        at Module._compile (module.js:413:34)
> remote:        at Object.Module._extensions..js (module.js:422:10)
> remote:        at Module.load (module.js:357:32)
> remote:        at Function.Module._load (module.js:314:12)
> remote:        at Module.require (module.js:367:17)
> remote:        
> remote:        npm ERR! Linux 3.13.0-71-generic
> remote:        npm ERR! argv "/tmp/build_f65e1cd8c6973d691eef143f131c848c/.heroku/node/bin/node" "/tmp/build_f65e1cd8c6973d691eef143f131c848c/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_f65e1cd8c6973d691eef143f131c848c/.npmrc"
> remote:        npm ERR! node v5.6.0
> remote:        npm ERR! npm  v3.6.0
> remote:        npm ERR! code ELIFECYCLE
> remote:        npm ERR! angular2-express-starter@1.0.0 postinstall: `gulp`
> remote:        npm ERR! Exit status 1
> remote:        npm ERR!
> remote:        npm ERR! Failed at the angular2-express-starter@1.0.0 postinstall script 'gulp'.
> remote:        npm ERR! Make sure you have the latest version of node.js and npm installed.
> remote:        npm ERR! If you do, this is most likely a problem with the angular2-express-starter package,
> remote:        npm ERR! not with npm itself.
> remote:        npm ERR! Tell the author that this fails on your system:
> remote:        npm ERR!     gulp
> remote:        npm ERR! You can get information on how to open an issue for this project with:
> remote:        npm ERR!     npm bugs angular2-express-starter
> remote:        npm ERR! Or if that isn't available, you can get their info via:
> remote:        npm ERR!     npm owner ls angular2-express-starter
> remote:        npm ERR! There is likely additional logging output above.
> remote:        
> remote:        npm ERR! Please include the following file with any support request:
> remote:        npm ERR!     /tmp/build_f65e1cd8c6973d691eef143f131c848c/npm-debug.log
> remote: 
> remote: -----> Build failed
> remote:        
> remote:        We're sorry this build is failing! You can troubleshoot common issues here:
> remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
> remote:        
> remote:        Some possible problems:
> remote:        
> remote:        - Node version not specified in package.json
> remote:        https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
> remote:        
> remote:        Love,
> remote:        Heroku
> remote:        
> remote: 
> remote:  !     Push rejected, failed to compile Node.js app
> remote: 
> remote: Verifying deploy....
> remote: 
> remote: ! Push rejected to howzer.
> remote: 
> To https://git.heroku.com/howzer.git
>  ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'https://git.heroku.com/howzer.git'
> ```

Heroku log:

> ```
> -----> Node.js app detected
> -----> Creating runtime environment
> 
>        NPM_CONFIG_LOGLEVEL=error
>        NPM_CONFIG_PRODUCTION=true
>        NODE_ENV=production
>        NODE_MODULES_CACHE=true
> -----> Installing binaries
>        engines.node (package.json):  unspecified
>        engines.npm (package.json):   unspecified (use default)
> 
>        Resolving node version (latest stable) via semver.io...
>        Downloading and installing node 5.6.0...
>        Using default npm version: 3.6.0
> -----> Restoring cache
>        Skipping cache restore (new runtime signature)
> -----> Building dependencies
>        Pruning any extraneous modules
>        Installing node modules (package.json)
> 
>        > angular2-express-starter@1.0.0 postinstall /tmp/build_f65e1cd8c6973d691eef143f131c848c
>        > gulp
> 
>        module.js:341
>        throw err;
>        ^
> 
>        Error: Cannot find module 'gulp-tslint'
>        at Function.Module._resolveFilename (module.js:339:15)
>        at Function.Module._load (module.js:290:25)
>        at Module.require (module.js:367:17)
>        at require (internal/module.js:16:19)
>        at Object.<anonymous> (/tmp/build_f65e1cd8c6973d691eef143f131c848c/gulpfile.js:4:14)
>        at Module._compile (module.js:413:34)
>        at Object.Module._extensions..js (module.js:422:10)
>        at Module.load (module.js:357:32)
>        at Function.Module._load (module.js:314:12)
>        at Module.require (module.js:367:17)
> 
>        npm ERR! Linux 3.13.0-71-generic
>        npm ERR! argv "/tmp/build_f65e1cd8c6973d691eef143f131c848c/.heroku/node/bin/node" "/tmp/build_f65e1cd8c6973d691eef143f131c848c/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_f65e1cd8c6973d691eef143f131c848c/.npmrc"
>        npm ERR! node v5.6.0
>        npm ERR! npm  v3.6.0
>        npm ERR! code ELIFECYCLE
>        npm ERR! angular2-express-starter@1.0.0 postinstall: `gulp`
>        npm ERR! Exit status 1
>        npm ERR!
>        npm ERR! Failed at the angular2-express-starter@1.0.0 postinstall script 'gulp'.
>        npm ERR! Make sure you have the latest version of node.js and npm installed.
>        npm ERR! If you do, this is most likely a problem with the angular2-express-starter package,
>        npm ERR! not with npm itself.
>        npm ERR! Tell the author that this fails on your system:
>        npm ERR!     gulp
>        npm ERR! You can get information on how to open an issue for this project with:
>        npm ERR!     npm bugs angular2-express-starter
>        npm ERR! Or if that isn't available, you can get their info via:
>        npm ERR!     npm owner ls angular2-express-starter
>        npm ERR! There is likely additional logging output above.
> 
>        npm ERR! Please include the following file with any support request:
>        npm ERR!     /tmp/build_f65e1cd8c6973d691eef143f131c848c/npm-debug.log
> -----> Build failed
> 
>        We're sorry this build is failing! You can troubleshoot common issues here:
>        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
> 
>        Some possible problems:
> 
>        - Node version not specified in package.json
>        https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
> 
>        Love,
>        Heroku
> 
>  !     Push rejected, failed to compile Node.js app
> ```

**Comment by vladotesanovic** [comment]
Gulp is moved to dependencies.

Demo app: https://express-angular2.herokuapp.com/
