### ISSUE TITLE
How to add other dependencies ?

### ISSUE THREAD

**Issue by NishantDesai1306** [vladotesanovic/angular2-express-starter#10]
i had instaled Local Storage module via npm but now when i try to run the app it gives me error 
Internal Server Error (500) for http://localhost:3000/h5webstorage

I had included the module in main.ts and in component where i need this package

**Comment by SimpleVictor** [comment]
Go into public/js/systemjs.config.js

**Comment by vladotesanovic** [comment]
as @VietAnhh suggested you should edit public/js/systemjs.config.js and add your dependencies. 

Here: https://github.com/vladotesanovic/angular2-express-starter/branches

You have few examples how you integrate: angularfire, underscore and googlemaps.

Follow same pattern as it is there.

**Comment by NishantDesai1306** [comment]
I have created one model file in server/models directory, after saving it
transpiles to commonjs

but when i build my project using "npm run develop" then it transpiles to
systemjs which throws error "System is not defined"

Surprisingly i also have decalred another model in same directory in
another file but it transpiles only to commonjs (thereby working properly)
