### ISSUE TITLE
Client in public

### ISSUE THREAD

**Issue by SwiftRabbit** [vladotesanovic/angular2-express-starter#11]
On the Heroku Website, it mentions that any Angular Code (.ts) that is client side should be found in public.  https://devcenter.heroku.com/articles/mean-apps-restful-api#connect-mongodb-and-the-app-server-using-the-node-js-driver Not sure if relevant.

**Comment by vladotesanovic** [comment]
Nope, TS should be compiled to JS before publishing on client.
