### ISSUE TITLE
moduleId Enhancement?

### ISSUE THREAD

**Issue by SimpleVictor** [vladotesanovic/angular2-express-starter#15]
I find it kind of tedious but is there a way to avoid having to state the full directory inside the templateUrl.

In the original angular 2 seed they have something like this

```
@Component({
   moduleId: module.id,
    templateUrl: tutorial-home-component.html
})
```

But in my case I have something like this

```
@Component({
    selector: 'WR-tutorial-home',
    directives: [SearchBarComponent],
    styleUrls: ['./client/modules/tutorial/home/tutorial-home.component.css'],
    templateUrl: './client/modules/tutorial/home/tutorial-home.component.html'
})
```

Any way you can incorporate that method of using moduleId. And if there is one already set up that I didn't know about how would I be able to?

**Comment by vladotesanovic** [comment]
Yep,

I can do this, only stuff that i need to change is to switch SystemJS with WebPack ( module.id is WebPack thing )

Then bundling and paths will be easier than now.
