### ISSUE TITLE
Module ./Observable not declared as a dependency.

### ISSUE THREAD

**Issue by erroldee** [vladotesanovic/angular2-express-starter#16]
I am getting a error

"bundle.min.js:1 Uncaught TypeError: Module ./Observable not declared as a dependency."

When I try to run your server.

Is there anything else i need to do?

**Comment by erroldee** [comment]
I only get this error why i try to use the systemjs builder bundle. I get an error whether i run bundle.js or bundle.min.js

**Comment by vladotesanovic** [comment]
Bundling is broken here, I am in process of switching SystemJS for WebPack here.

**Comment by vladotesanovic** [comment]
This is fixed with latest commit
