### ISSUE TITLE
run the node server as a service

### ISSUE THREAD

**Issue by mquentin** [vladotesanovic/angular2-express-starter#19]
Hello,

I am struggling to run you app as a service (in view to have it running on my remote server). Do you know how to run it with forever (https://github.com/foreverjs/forever) ? Should I run the scripts tsc -w -p ./client, tsc -w -p ./server before and then run a specific JS file with forever ?

I know that my questions seem a bit stupid but I would be pleased if you could enlighten me about the steps of this script : "develop": "concurrently \"tsc -w -p ./server\" \"tsc -w -p ./client\" \"nodemon ./server/bin/www\" ".

**Comment by vladotesanovic** [comment]
Yep,

You need to compile TypeScript to JavScript, than to run compiled stuff with Forever.

Check it here:
https://github.com/vladotesanovic/angular2-express-starter/blob/master/package.json#L9

**Comment by mquentin** [comment]
Thanks !
