### ISSUE TITLE
error when I deploy to heroku

### ISSUE THREAD

**Issue by mcferren** [vladotesanovic/angular2-express-starter#2]
https://new-job-blues.herokuapp.com/rxjs/observable/PromiseObservable.js 

Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by vladotesanovic** [comment]
Yes, this happen because they updated to Angular Beta.7 last night, and deps where inconsistent. Repository is fixed to Beta 7, updates will not break anything. It is tested on heroku.
