### ISSUE TITLE
Development vs Production mode

### ISSUE THREAD

**Issue by mquentin** [vladotesanovic/angular2-express-starter#20]
Hello,

Could-you explain the steps to produce the bundle.min.js of the application for the production mode ?

`npm run bundle:prod`

then 

`npm run postinstall`

then 

`npm run develop`

?

**Comment by vladotesanovic** [comment]
yep,

In local, just run

``` bash
npm run bundle:prod
```

When you are deploying your app to Heroku ( for instance )
Uncomment this

``` html
<script src="js/bundle.min.js"></script>
```

And comment

``` html
<script src="assets/js/systemjs.config.js"></script>
<script>
    System.import('app').catch(function(err) { console.error(err); });
</script>
```

Inspect code here, you will see that i am loading everything from bundle
https://express-angular2.herokuapp.com/#/home

**Comment by mquentin** [comment]
ok and when the build is done, which script should I use to run the serveur, npm run develop ?

**Comment by vladotesanovic** [comment]
If you are developing, then load application from systemjs.config.js ( don't build anything )

If you are running it in production, use `npm run production` after `npm run bundle:prod`

**Comment by mquentin** [comment]
ok thanks, but I don't see any "production" script in your package.json... I might have missed something

**Comment by vladotesanovic** [comment]
Sorry, it is `forever`

**Comment by mquentin** [comment]
thanks
