### ISSUE TITLE
outDir for transpiled code?

### ISSUE THREAD

**Issue by muleyprasad** [vladotesanovic/angular2-express-starter#21]
Any plans to configure an outDir for transpiled code and then bundle it?

**Comment by vladotesanovic** [comment]
I ma doing it right now, just run:

`npm run bundle:prod` to bundle your app into one file: bundle.min.js

**Comment by muleyprasad** [comment]
well that's good for production but if I am to use this as a starter kit then the transpiled files in folders like server or client is an eyesore.

**Comment by vladotesanovic** [comment]
Ah i see what you mean... 

I am using WebStorm as primary IDE, and if i turn on TypeScript service, than WebStorm hide .js and .js.map files.

I know that VisualCode have similar option.

What IDE you use?

**Comment by muleyprasad** [comment]
VS Code.

**Comment by vladotesanovic** [comment]
http://stackoverflow.com/a/32604188

**Comment by muleyprasad** [comment]
That's a workable solution but IMO having compiled stuff in a 'dist' something folder would be a lot cleaner. Would you accept accept a pull request?

**Comment by vladotesanovic** [comment]
This is implemented now!
