### ISSUE TITLE
Prod mod

### ISSUE THREAD

**Issue by mquentin** [vladotesanovic/angular2-express-starter#22]
Hello,

I am trying to set up the prod mode of the angular2-express-starter. I succeed in building the bundle.min.js which I run using the script develop : _concurrently "tsc -w -p ./server" "tsc -w -p ./client" "nodemon ./server/bin/www"_ (after having the index.html in "prod mode".

The issue is when run the app in dev mode, it runs perfectly but in prod mode, the angular app cannot load the home.module and contact.module...

**zone.js:101 GET http://localhost:3000/client/modules/home/home.module 500 (Internal Server Error)**

**EXCEPTION: Error: Uncaught (in promise): Error: Error: XHR error (500 Internal Server Error) loading http://localhost:3000/client/modules/home/home.module**

Do you guys have any ideas why the modules cannot be loaded once the _tools/builder.js_ build done ?

Regards

**Comment by vladotesanovic** [comment]
If you are developing in local environment, just run

``` bash
npm run develop
```

and uncomment 

``` html
 <script src="assets/js/systemjs.config.js"></script>
        <script>
            System.import('app').catch(function(err) { console.error(err); });
        </script>
```

while commenting

``` html
<script src="assets/js/bundle.min.js"></script>
```

![image](https://cloud.githubusercontent.com/assets/738638/18230724/dad92810-72a4-11e6-9671-294afba9ac06.png)

**Comment by mquentin** [comment]
Hello, 
I understand that the line
`<script src="assets/js/bundle.min.js"></script>`

is used to launch the app with the compiled / minified / uglified JS file : bundle.min.js.

The point is whenever I build the bundle.min.js with your script `npm run bundle:prod` I have got some issues with the child modules home.module and contact.module.

**EXCEPTION: Error: Uncaught (in promise): Error: Error: XHR error (500 Internal Server Error) loading http://localhost:3000/client/modules/home/home.module**

I would like to know if you guys have the same problem...

**Comment by vladotesanovic** [comment]
Oh, sorry, i realize now.

You are using old version of this repository, in that version in router, i am using Lazy Loading for modules, which is not possible to bundle. I switched to normal routing than. Compare main routing file ( routing.ts ) with your current

**Comment by mquentin** [comment]
Ok perfect ! Don't be sorry, I should have checked your new version.
