### ISSUE TITLE
couldnt load external node modules 

### ISSUE THREAD

**Issue by arunmettle** [vladotesanovic/angular2-express-starter#25]
spent 3 hours still no luck . I am trying to load "ng-bootstrap " but it doesnt load the modules from system js. 
Guidance needed in loading the external modules 

`var isPublic = typeof window != "undefined";

/**
- System configuration for Angular 2 samples
- Adjust as necessary for your application needs.
  */
  (function (global) {
  System.config({
      paths: {
          // paths serve as alias
          'npm:': (isPublic) ? '/' : 'node_modules/'
      },
      // map tells the System loader where to look for things
      map: {
          // our app is within the app folder
          app: 'client',
          // angular bundles
          '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
          '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
          '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
          '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
          '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
          '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
          '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
          '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
          // other libraries
          'rxjs':                       'npm:rxjs',
          'angular2-in-memory-web-api': 'npm:angular2-in-memory-web-api',
          'angular2-jwt':               'npm:angular2-jwt/angular2-jwt.js',
          'ng-semantic':                'npm:ng-semantic',
          '@ng-bootstrap':          'npm:@ng-bootstrap'
      },
      // packages tells the System loader how to load when no filename and/or no extension
      packages: {
          app: {
              main: './main.js',
              defaultExtension: 'js'
          },
          rxjs: {
              defaultExtension: 'js'
          },
          'angular2-in-memory-web-api': {
              main: './index.js',
              defaultExtension: 'js'
          },
          'ng-semantic': {
              main: 'ng-semantic',
              defaultExtension: 'js'
          },
          '@ng-bootstrap':         { main: 'ng-bootstrap', defaultExtension: 'js' }
      }
  });
  })(this);
  `

**Comment by vladotesanovic** [comment]
Import like this:

``` bash
import {NgbModule} from '@ng-bootstrap/ng-bootstrap';
```

``` javascript
...
 map: {
   '@ng-bootstrap': 'npm:@ng-bootstrap/ng-bootstrap/bundles'
 }
...

packages: {
....
  '@ng-bootstrap': {
    main: 'ng-bootstrap',
    defaultExtension: 'js'
  }
}
 ...
...
```
