### ISSUE TITLE
Fetch API cannot load about:blank

### ISSUE THREAD

**Issue by protzi** [vladotesanovic/angular2-express-starter#27]
Hello, this message i have in browser after server started
`zone.min.js:1 Fetch API cannot load about:blank. URL scheme "about" is not supported.`

Could you explain more about shared module ? `static forRoot`

**Comment by arunmettle** [comment]
I am facing the same error too on top of another  issue #25

**Comment by vladotesanovic** [comment]
Guys, this was zone.js issue https://github.com/angular/angular-cli/issues/2117

Use this file in your app:
https://github.com/vladotesanovic/angular2-express-starter/commit/c6a787f6f21d13201fb5a99311fef226daa9ddb0

@arunmettle I will check your issue with ng-boostrap
