### ISSUE TITLE
bad digest name

### ISSUE THREAD

**Issue by paklei** [vladotesanovic/angular2-express-starter#28]
When I clone the repository do the changes in the index file for dev work; I have the error 

> "bad digest name"

The config.ts file is:

```
export const secret: string = "RbBQqA6uF#ms%F8s7h*?@=95HUm&DGMDd6zLF74XzWQ6dtwXSJwBX#?gL2JWf!";
export const length: number = 128;
export const digest: string = "RbBQqA6uF#msRF8s";
```

but if I change to the next code the login works:

```

export const secret: string = "RbBQqA6uF#ms%F8s7h*?@=95HUm&DGMDd6zLF74XzWQ6dtwXSJwBX#?gL2JWf!";
export const length: number = 512;
export const digest: string = "sha512";
```

But the token's value is indefined after "login".

**Comment by vladotesanovic** [comment]
Yes,

This was my bad, digest should be sha256 or sha512 ( i put sha256 )

For testing purpose i put hard-coded values for hashed password and salt ( which should be changed in case we change digest value ). I did that now, everything works.
