### ISSUE TITLE
Problem uploading to AWS?

### ISSUE THREAD

**Issue by Hagafny** [vladotesanovic/angular2-express-starter#29]
Hey

I tried to upload your project to AWS via Elastic Beanstalk. I get the error "missing script: start". What are the steps that I need to do in order to successfully upload it to AWS?

**Comment by SimpleVictor** [comment]
You would have to set up the script command inside the settings on AWS . I believe the default would be node ./bin/www or npm start

**Comment by vladotesanovic** [comment]
as @VietAnhh suggested you probably need `npm start` in package.json ( i can add it also in project )

Something like

``` javascript
scripts: [
  ...
  start: 'node ./server/bin/www'
  ...
]
```

**Comment by Hagafny** [comment]
Thanks for the reply.
Of course, I tried writing several commands before issuing this. I wrote the npm start script as you suggested and now also tried VietAnnhh suggestion. Both result in:
Error: Cannot find module '/var/app/current/bin/www'

I've been struggling with this for quite some time. Do you happen to know what's going on?
I bet there's some people who would like to use your project to AWS and not just Heroku. Might as well make it compatible for both ;)

**Comment by vladotesanovic** [comment]
Yep, i need to setup AWS than, i don't work with it.

Is it problem with path? Where app is located in your server? `/var/app` ?

**Comment by Hagafny** [comment]
I did not touch anything in your code yet - Just cloned it and automatically uploaded it to AWS. Everything is in its original place

**Comment by Sprogrammer007** [comment]
your uploading to  Elastic Beanstalk which is a EC2 but  Elastic Beanstalk is sort of different. Make sure your config options are correct for  Elastic Beanstalk there is an option where you can put in the command to execute and start your server. You would add "node ./server/bin/www" this line without the start in front of it.
