### ISSUE TITLE
Can you please add styleUrls and templateUrl to this repo too

### ISSUE THREAD

**Issue by mcferren** [vladotesanovic/angular2-express-starter#3]
I added these to my angular2-express-starter repo:

styleUrls: ["components/container/container.css"],
templateUrl: "components/container/container.html"

but I am getting a 404 (Not Found) because I think my css and html are not being written to the client directory

**Comment by vladotesanovic** [comment]
Sorry for late answer.

You can create css and html files beside component class in src folder now. ( i put that in gulp as task )

Please, clone or update repository and try.
