### ISSUE TITLE
adding mongoose functionality

### ISSUE THREAD

**Issue by paklei** [vladotesanovic/angular2-express-starter#30]
I'm trying to add a real db functionality, I wrote a user model and also I was trying to add a botton to the main navbar in the app.component.ts template, but I don't kwon why the code is the same even when I change it.

I test the insert and it works, when the signup button is pressed, it returns the salt but the hashed password don't ... I think this is because the template hardcoded on app.component.ts is always the same.

I can't do a pull requests, but I have a fork in the following link:
 https://github.com/paklei/angular2-express-starter.git

I just have 3 days studying the MEAN stack, maybe I'm doing few things wrong but I really want to learn and help to improve this project.

**Comment by vladotesanovic** [comment]
First you need to uncomment development mode here:
https://github.com/paklei/angular2-express-starter/blob/master/public/index.html

I'll need to check your code / repo to see what happening.

**Comment by paklei** [comment]
Hi Vlado!
I think I got it, I add the login and signup functinality on my branch. If you think this could be usefull for this repo, feel free for pull it.

I'm not sure about the perfomance of that code (I mean, I think that can be more efficient) ... but I'm sure it works.

Thanks for your help and your time.
