### ISSUE TITLE
Type 'Response' is not assignable to type '{ hashed: string; salt: string; }

### ISSUE THREAD

**Issue by nkthuan** [vladotesanovic/angular2-express-starter#31]
After performing the steps in Readme.md and start the app by "npm run develop", the following error occurs at the command line:
[1] client/app.component.ts(75,21): error TS2322: Type 'Response' is not assignable to type '{ hashed: string; salt: string; }'.
[1]  Property 'hashed' is missing in type 'Response'.

Is this a problem in the code itself or maybe a problem of the tsc version ?

My tsc version is 1.6.2

**Comment by ghost** [comment]
Got same error

**Comment by vladotesanovic** [comment]
Ok i will take a look

**Comment by ghost** [comment]
just write localhost:3000 in browser and hit enter after enter npm run develop in cmd

**Comment by vladotesanovic** [comment]
Small typing issue
