### ISSUE TITLE
Refreshing route fails

### ISSUE THREAD

**Issue by georgeedwards** [vladotesanovic/angular2-express-starter#33]
So I have modified the client folder a bit and added some routes and components. Now if I am on a route e.g. `http://localhost:3000/tutorial/chapter/0` and I refresh the page, rather than seeing what I saw before the refresh, I get:

```
{"error":{"errno":-4058,"code":"ENOENT","syscall":"stat","path":"C:\\Users\\George\\Downloads\\angular2-express-starter-master\\angular2-express-starter-master\\server\\ng2\\views\\index.html","expose":false,"statusCode":404,"status":404},"message":"ENOENT: no such file or directory, stat 'C:\\Users\\George\\Downloads\\angular2-express-starter-master\\angular2-express-starter-master\\server\\ng2\\views\\index.html'"}
```

I haven't really modified the `app.ts` file in sever.

**Comment by georgeedwards** [comment]
Aha! The issue is that you shouldn't use `<base href=".">`, it should be `<base href="/">`. I'll submit a PR.

**Comment by vladotesanovic** [comment]
This is fixed with new setup: angular-cli - webpack
