### ISSUE TITLE
Serves error message to browser

### ISSUE THREAD

**Issue by Shakyamuni177te** [vladotesanovic/angular2-express-starter#37]
After cloning, npm installing and running `npm start`, server starts fine, but in the browser, at port 4300 I'm seeing:

```
{"error":{},"message":"Not Found"}
```

Instead of the expected welcome/it works type message. Port 4200 serves nothing.

**Comment by vladotesanovic** [comment]
Ok,

Do you have any errors or warnings in console?

After `npm start` you should have:

Client ( Angular 2 ): http://localhost:4200
REST API: http://localhost:4300

In production mode, everything is on same port.

**Comment by Shakyamuni177te** [comment]
At http://139.162.246.138:4300 (I don't have a GUI available from my server so I have to serve remotely, but that shouldn't be related), in the console I'm seeing:

http://139.162.246.138:4300/favicon.ico 500 (Internal Server Error)

And the error specified above. 

http://139.162.246.138:4200 console shows:

GET http://139.162.246.138:4200/ net::ERR_CONNECTION_REFUSED
2Navigated to data:text/html,chromewebdata
http://139.162.246.138:4200/:1 GET http://139.162.246.138:4200/ net::ERR_CONNECTION_REFUSED
http://139.162.246.138:4200/:1 GET http://139.162.246.138:4200/ net::ERR_CONNECTION_REFUSED

Browser (when connected to port 4200) shows:

This site can’t be reached
139.162.246.138 refused to connect.
Search Google for 139 162 246 138 4200

I have changed nothing but the localhost to the remote IP, so I can test.

Ports 4200 and 4300 are showing as open when running `ufw status verbose`

**Comment by Shakyamuni177te** [comment]
Update: I have tried moving favicon.ico to the /src/assets directory, which, from an inspection of the angular-cli file seems to be where the favicon.ico file is expected, but nevertheless am still receiving the same 500 error...

**Comment by Shakyamuni177te** [comment]
Update: downloaded and cloned fresh repo, with improved path inclusion. Same issue. :/

**Comment by Shakyamuni177te** [comment]
Update: dropped back to node 6.9.1. Still seeing the following error at `npm install`:

```
node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.1-node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.1 and node@6.9.1 (node-v48 ABI) (falling back to source compile with node-gyp) 
```
Attempting to find workaround.

**Comment by vladotesanovic** [comment]
Hey,

What you are trying to do here? You are cloning and installing directly on server?

**Comment by Shakyamuni177te** [comment]
Yeah. Cloning and installing directly to my remote server.
