### ISSUE TITLE
The start command is not cross platform

### ISSUE THREAD

**Issue by preischeld** [vladotesanovic/angular2-express-starter#41]
The start command is not cross platform because the & character does not work on windows. This means that running on windows results in the express app never starting.

Recommend using concurrently since you are already doing so for other things.
    "start": "concurrently --kill-others \"ng serve --proxy-config proxy.conf.json\" \"npm run _server:run\"",

**Comment by TreyOverton** [comment]
I have no idea how you found that, but kudos. I was just struggling with the same thing.

When you put that line in package.json, you do need to escape the inner double quotes:
"start": "concurrently --kill-others \"ng serve --proxy-config proxy.conf.json\" \"npm run _server:run\"",

**Comment by vladotesanovic** [comment]
i am not using windows, i ll need more help on this

This: `"build": "ng build --prod --output-path=dist/client && npm run _server:build"`

Will not work either? 

http://stackoverflow.com/questions/8055371/how-to-run-two-commands-in-one-line-in-windows-cmd/8055430#8055430

**Comment by preischeld** [comment]
That command actually works fine for that example. The && works in windows while & does not. I did try changing the start command to also do && before submitting this issue, but I believe the && waits for the first command to finish before starting the second. So basically, you could either have the front end running or the back end running, but not at the same time using &&. But for commands where it does not matter if the first finishes and then starts the second, && will be fine (for windows).

http://stackoverflow.com/questions/30950032/how-can-i-run-multiple-npm-scripts-in-parallel

**Comment by preischeld** [comment]
@AaronOverton You are absolutely correct. My code was set up with the escaping properly, but it must have not copied over to this post for some reason. Thanks!.
