### ISSUE TITLE
http://localhost:4300 not working 

### ISSUE THREAD

**Issue by asingh12541** [vladotesanovic/angular2-express-starter#42]
{"error":{},"message":"Not Found"}

**Comment by vladotesanovic** [comment]
That is API side

For client app go to: http://localhost:4200

**Comment by asingh12541** [comment]
haven't you made the api side public

**Comment by duard** [comment]
I like to access the API side via browser

**Comment by vladotesanovic** [comment]
try with: http://localhost:4300/api/public/simple
