### ISSUE TITLE
Misunderstanding or feature request.

### ISSUE THREAD

**Issue by artemzi** [vladotesanovic/angular2-express-starter#45]
@vladotesanovic  as i see for now back end code used for access api/* routes and in production it's just served from angular 2 build in client. But if i want to have some set of static pages (for example for landing) which is not part of angular 2.

Is it possible to have static node templates and redirect to angular 2 app only for some specific url group ?

**Comment by vladotesanovic** [comment]
Sure in app.ts you can do this:

**production**
``` app.use("/pages", express.static(path.join(__dirname, '/../assets/pages'))); ```

**development**
``` app.use("/pages", express.static(path.join(__dirname, '/../../src/assets/pages'))); ```

( paths are not tested... )

Than in that folder **src/assets/pages** create your html files.

**Comment by artemzi** [comment]
@vladotesanovic and do i have possibility to change path for angular 2 app? For example i want to have static (or node templates) page on `localhost:4300/` and angular 2 app on `localhost:4300/client/#dashboard`. If i just add path into `app.use` with static path it cannot find angular build files. (errors in GET: /inline.d41d8cd98f00b204e980.bundle.js 500 (Internal Server Error), and other build files)

**Comment by vladotesanovic** [comment]
You can't do that in development mode, at least on easy way.

If you want to run in production like that, than you need to change in app.ts:  ```` app.use("/client", express.static(path.join(__dirname, '/../client'))); ```

Angular2 app will be served from: **your.host/client**

**Comment by artemzi** [comment]
@vladotesanovic this is what i describe in previous message, it's not working, if i add `/client` to use `app.use("/client", express.static(path.join(__dirname, '/../client')));` i receive errors, that all *.bundle.js files not found.

**Comment by artemzi** [comment]
@vladotesanovic i have try add it in local setup and in heroku nothing works`app.use("/client", express.static(path.join(__dirname, '/../client')));` and when i go to `<URL>/client` => get 500 error, cannot find angular build files.

**Comment by vladotesanovic** [comment]
Ok, you can do like this ( i tested it )

change:
https://github.com/vladotesanovic/angular2-express-starter/blob/master/src/index.html#L6

to: ``` <base href="./"> ``` ( for angular2 router )

Create file inside: ``` src/assets/pages/index.html ``` put inside whatever you want.

change app.ts: https://github.com/vladotesanovic/angular2-express-starter/blob/master/server/app.ts#L31

to be

```javascript
// in production mode run application from dist folder
  app.use("/client", express.static(path.join(__dirname, '/../client')));
  app.use(express.static(path.join(__dirname, '/../client/assets/pages')));
```

build application wtih: ``` npm run build ```

test it locally with:

```bash
~/my/project/dir NODE_ENV=production node dist/server/bin/www.js
```
you should get your index.html page on: http://localhost:4300

on http://localhost:4300/client angular2 app

I can't commit this to master branch, because this is not feature or bug

**Comment by artemzi** [comment]
@vladotesanovic yes thanks this is my mistake i completely forgot about 'base href'
