### ISSUE TITLE
Run fails when importing new modules

### ISSUE THREAD

**Issue by joandvgv** [vladotesanovic/angular2-express-starter#53]
I've been having the same issue with different front-end frameworks required modules. 
`ERROR in Unexpected value 'NgSemanticModule in /home/joandv/angular2-express-starter/node_modules/ng-semantic/ng-semantic.d.ts' imported by the module 'AppModule in /home/joandv/angular2-express-starter/src/app/app.module.ts'
[0] 
`

Same happens with angular2-materialize module. I thought the problem was with that one but now i've chosen one of your one development and it still fails.  
![image](https://cloud.githubusercontent.com/assets/19196871/21736995/61ad0dfe-d44b-11e6-9c33-87f1c49b7c03.png)

**Comment by vladotesanovic** [comment]
NgSemanticModule and probably angular2-materialize ( i didn't try ) are not AOT ready.

If you switch off AOT, than they will work.

**Comment by joandvgv** [comment]
Thanks for your reply. 
I am new to angular2 and those concepts, I've been reading a bit about it.
How do I switch it off? Thanks!

**Comment by vladotesanovic** [comment]
You can switch off with setting: ```aot=false``` here:

https://github.com/vladotesanovic/angular2-express-starter/blob/master/package.json#L9

**Comment by joandvgv** [comment]
Thanks!

**Comment by joandvgv** [comment]
Hi there Vlado! I don't know if this is realted since I have already disabled aot for production. But i get this error when modifying evironment.ts production var to true. 
![image](https://cloud.githubusercontent.com/assets/19196871/21873815/832f0428-d847-11e6-8d42-548eacc9ef1f.png)
This does not happen when building normally.
