### ISSUE TITLE
Error with npm install  "webpack.LoaderOptionsPlugin is not a constructor"

### ISSUE THREAD

**Issue by achreftlili** [vladotesanovic/angular2-express-starter#54]
Hey every body i got this error today about " webpack.LoaderOptionsPlugin is not a constructor"
when i run "npm install"  any idea?

![ofii](https://cloud.githubusercontent.com/assets/4409405/21925361/70d71266-d97d-11e6-87fd-47b48839bc96.png)
 
Versions:
node -v
v6.9.4
 npm -v
3.10.10

**Comment by vladotesanovic** [comment]
Can you try now, with latest updates?

**Comment by achreftlili** [comment]
Thanks Vlado it's working  :+1:
