### ISSUE TITLE
You may need an appropriate loader to handle this file type. | import { enableProdMode } from '@angular/core';

### ISSUE THREAD

**Issue by ndeufemia** [vladotesanovic/angular2-express-starter#56]
### I didn't do anything but cloning this repo and running "npm install" and get this error at :

> Failed at the angular2-express-starter@1.0.0 build script 'ng build --prod --sm=false --aot=true --output-path=dist/client && npm run _server:build'.

**angular logs this error some lines above:**

```
> angular2-express-starter@1.0.0 build D:\Git\#coop\bee-companion
> ng build --prod --sm=false --aot=true --output-path=dist/client && npm run _server:build

Hash: 21b17b65e95e626c6f8d
Time: 1752ms
chunk    {0} styles.6fc8d9b42ce94f693a6f.bundle.css (styles) 4.74 kB {2} [initial] [rendered]
chunk    {1} main.c9784bf6d3293742e791.bundle.js (main) 504 bytes [initial] [rendered]
chunk    {2} inline.36206a9e576750524539.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in ENOENT: no such file or directory, open 'D:\Git\modal.component.html'

ERROR in ./src/main.ts
Module parse failed: D:\Git\#coop\bee-companion\node_modules\@ngtools\webpack\src\index.js!D:\Git\#coop\bee-companion\src\main.ts Unexpected token (4:21)
You may need an appropriate loader to handle this file type.
| import { enableProdMode } from '@angular/core';
| import { environment } from './environments/environment';
| import { coop } from /bee-companion/src / app / app.moduleNgFactory;
| from;
| './../../.ngfactory';
 @ multi ./src/main.ts
```

I have already tried setting `--aot=false ` on the start script, but it didn't help.

Any suggestions?

npm-debug.log added to the attachments.
[npm-debug.txt](https://github.com/vladotesanovic/angular2-express-starter/files/739023/npm-debug.txt)

thanks in advance!

**Comment by vladotesanovic** [comment]
Can you give me more information about your problem:

Operating system:
Node version you are using:
Do you use latest version of this repo?
