### ISSUE TITLE
Access to html server from another computer on the local network

### ISSUE THREAD

**Issue by ghost** [vladotesanovic/angular2-express-starter#57]
Hi,

I just spent several hours trying and figuring why on the server computer I can access using http://localhost:4200 or http://127.0.0.1:4200, but I can't from another computer using http://192.168.0.10:4200 (this ip being the server's).

However, I can access the API through http://192.168.0.10:4300/api/xxxx

StackOverflow has several threads on the general issue (eg for node projects not this starer kit) but none of the solutions I understand works. It's not a firewall issue, nor a network one. One apparent solution would be to replace 127.0.0.1 by 0.0.0.0 somewhere, I guess that would be in angular-cli but that hacking it is way above my level of programming (I'm an amateur dev).

I'm really blocked here since I can't efficiently test my project on other devices (tablet, phone). What works is to upload the whole thing to heroku and from there, everything works fine.

So help would be really appreciated!

Guénaël

**Comment by vladotesanovic** [comment]
Maybe this answer can be helpful to you:

https://github.com/vladotesanovic/angular2-express-starter/issues/46#issuecomment-263519767

**Comment by ghost** [comment]
Hi Vlado,

Thanks for your super quick reply yesterday (and for the whole project!).

I haven't succeeded in using forever for my use. But I have found that inserting "--host 0.0.0.0" in the "start" command of the package.json works: 
`    "start":         "concurrently --kill-others \"ng serve --host 0.0.0.0 --proxy-config proxy.conf.json\" \"npm run _server:run\"",`

I can now access the website from another computer using http://192.168.0.10:4200

Alas, the proxy configuration doesn't work from that other computer (but it does locally). My proxy conf is:
`{
  "/api": {
    "target": "http://127.0.0.1:4300",
    "secure": false
  }
}
`
So the html page is served but the API doesn't work when accessing from another computer. That is progress but not there yet. Any clue?
