### ISSUE TITLE
Workaround proposition for nasty webpack / uglifyJS bug

### ISSUE THREAD

**Issue by ghost** [vladotesanovic/angular2-express-starter#67]
Hi,

I just upgraded from an earlier version of your great starter. Everything went fine, except this well-know bug that appears in prod mode only : "UglifyJs SyntaxError: Unexpected token"

The solution (1) from the webpack team however doesn't work for the starter, since the change made on the /node_modules/webpack/package.json file will not be reflected on Heroku (but works locally of course).
(1) [https://github.com/webpack/webpack/issues/4394](https://github.com/webpack/webpack/issues/4394)

The workaround I found is to install this package **in the prod dependencies**:
npm install --save uglify-js@github:mishoo/UglifyJS2#harmony

I'm an amateur dev, so I can't tell how relevant this is. Just trying to avoid others loosing as much time as I did.

And thanks again for this starter, it's super helpful.

**Comment by appodeepa** [comment]
@guenam - thank you dude, saved me a lot of time.
