### ISSUE TITLE
Creating another project Angular app

### ISSUE THREAD

**Issue by zilions** [vladotesanovic/angular2-express-starter#69]
Thought I'd ask before attempting to implement this myself.

I'm wanting to add another separate Angular2 app into the project that shares the same server.

Currently, there is `src` (which builds to be `client`), and I'm wanting to add `admin` so that I can use `express-subdomain` to route all `admin.mydomain.com` requests to that subdomain's static content. I would also have to add to the build process so that I have dist folders `client`, `server` and `admin`.

What would be your suggestion on the best approach for this?

**Comment by vladotesanovic** [comment]
Is this something that can help you:

https://yakovfain.com/2017/04/06/angular-cli-multiple-apps-in-the-same-project/
