### ISSUE TITLE
Getting errors on @angular/forms when following the "Development" column on README

### ISSUE THREAD

**Issue by frostkisaragi** [vladotesanovic/angular2-express-starter#7]
There are 2 errors and they are as follows. It looks like it's looking for the @angular/forms dependency:

zone.js:101 GET http://localhost:3000/@angular/forms/ 500 (Internal Server Error)

(index):22 Error: Error: XHR error (500 Internal Server Error) loading http://localhost:3000/@angular/forms(…)

**Comment by vladotesanovic** [comment]
Tnx for reporting, 

Now it is fixed to last Angular rc.4 with forms.

**Comment by frostkisaragi** [comment]
Cool. Thanks, man! Gonna try again when I get home.
