### ISSUE TITLE
Question on an issue with IOs and internet explorer 11

### ISSUE THREAD

**Issue by ghost** [vladotesanovic/angular2-express-starter#70]
Hi,

My project based on your starter appears not to load on any browser on my iPhone 4s (IOs 9.3.5), nor on Internet Explorer 11 on the windows desktop (but it does on Edge, Chrome & Firefox [latest versions]  ).

By not loading, I mean the "moving circle" appears but it doesn't go further. The console stays empty.

So I checked the demo app:
https://express-angular2.herokuapp.com/

The result is slightly different since the demo loads on my iphone but not on Internet Explorer 11.

I am wondering if others here have met the same issue. Usual resources (Google, StackOverflow, GitHub) are silent on this.

Any clues? I don't know where to start my investigation. The bug may well be in Angular or WebPack, or of course in my own code.

**Comment by vladotesanovic** [comment]
Answer is in commit :)

I m not sue about iPhone 4s... If Angular 2 support it, than this repo will

**Comment by ghost** [comment]
It's me... again! ;-) 

Just to let you know: I checked the demo app on IE11, everything fine. On my iPhone, the demo loads now but the "get weather data" and the "add feed" buttons don't work (on all 4 browsers I tried).

So I'll keep on investigating a possible issue between angular and iOs9/iPhone4s.

**Comment by ghost** [comment]
Hi @vladotesanovic! Just to let you know that it appeared to be a package I used called limax. It slugs urls. So everything is ok now.
