### ISSUE TITLE
ERROR in Unexpected value 'ExternalModule' when npm start

### ISSUE THREAD

**Issue by Jayliu95** [vladotesanovic/angular2-express-starter#76]
I am getting the following error message :  "
ERROR in Unexpected value 'ExternalModule in path/node_modules/angular-2-data-table/dist/index.d.ts' imported by the module 'AppModule in path/src/app/app.module.ts'. Please add a @NgModule annotation."

in my app.module.ts file:

import {PushNotificationsModule, SimpleNotificationsModule} from "angular2-notifications/dist";
import {DataTableModule} from "angular-2-data-table/dist";

@NgModule({
  imports: [
    BrowserModule,
    CommonModule,
    FormsModule,
    HttpModule,
    RouterModule,
    routing,
    DataTableModule,
    PushNotificationsModule,
    SimpleNotificationsModule
  ],

I do see the external modules in node_modules

**Comment by vladotesanovic** [comment]
I don't think this error is associated with this repository. It is more with DataTableModule.

Can you try importing from `angular2-notifications` instead of `angular2-notifications/dist`
