### ISSUE TITLE
error TS2345: Argument of type,  in server/routes/login.ts

### ISSUE THREAD

**Issue by erisitohang** [vladotesanovic/angular2-express-starter#77]
I'm getting an error when try to run the build

```sh
> angular2-express-starter@1.0.0 _server:build /angular2-express-starter
> tsc -p ./server

server/routes/login.ts(46,33): error TS2345: Argument of type '{ user: string; permissions: undefined[]; }' is not assignable to parameter of type 'string | object | Buffer'.
  Object literal may only specify known properties, and 'user' does not exist in type 'string | object | Buffer'.
```

**Comment by EnslavedEagle** [comment]
Here's a temporary workaround for this problem, you just need to move the provided object to a separate variable:

```
const data = {
    user: user.username,
    permissions: []
};
const token = sign(data, secret, { expiresIn: "7d" });
```

The problem seems to be laying in how the TypeScript interprets the code.

**Comment by imgregduh** [comment]
I was able to get around this error by changing this line 

`const token = sign({user: user.username, permissions: []}, secret, { expiresIn: "7d" });`

to

`const token = sign(Object.create({user: user.username, permissions: []}), secret, { expiresIn: "7d" });` 

Located in server/routes/login.ts

**Comment by vladotesanovic** [comment]
This was caused by TypeScript version
