### ISSUE TITLE
Can't get some of the ng-semantic components working

### ISSUE THREAD

**Issue by hernan91** [vladotesanovic/angular2-express-starter#8]
**The steps i followed:**
- Created a new project by cloning the repo.
- _npm install_
- Enabled the development mode in _public/index.html_.
- Add `<button class="ui button" smDirTooltip="text..." smDirPosition="right center">Hover me</button>` at the top of the _home.component.html_ file.
- Did _npm run develop_ an compiled successfully.

**The problem:**
No "text..." on hover like in [this example](https://ng-semantic.herokuapp.com/#/elements/popup).

Just followed those steps. Pretty sure i'm missing something, that would be? Thanks for your time.

**Comment by vladotesanovic** [comment]
Hey, 

Sorry for late answer.

Did you manage to fix issue? 
Did you forget to comment out bundle.min.js version?

Did you publish your code anywhere so i can take a look?
