### ISSUE TITLE
Changes are delayed

### ISSUE THREAD

**Issue by high-malloy** [vladotesanovic/angular2-express-starter#82]
When I make a change, simple HTML change such as adding a new route to the file "top-navigation.component.html", the change is only visible in client after an additional change... 

Webpack compiled successfully everytime.

The second change is not visible until another change is added and webpack compiled again.

**Comment by vladotesanovic** [comment]
This is well known issue caused by your OS, nothing to do with this repo

**Comment by ducminhn** [comment]
I got the same issue. After couple hours finding the solution for this, I got it resolved by adding `--poll=1000` to the `ng server` command in package.json

Hope this can help!
Cheers
