### ISSUE TITLE
Deploy package.json

### ISSUE THREAD

**Issue by oscarcalvo** [vladotesanovic/angular2-express-starter#83]
Hi Vlado:

I have doubts about package installation. If I have to deploy only dist folder, how server knows about what packages node needs? I understand I need to deploy package.json manually, right?

Thanks

**Comment by high-malloy** [comment]
Do this:

1. Pull on the production server to have ALL the files of the project on the server that are not generated.
2. Run npm install.
3. Run npm run build.
4. Start the server with the server file (www.js) from the DIST folder.

**Comment by oscarcalvo** [comment]
Hey @high-malloy thanks.
