### ISSUE TITLE
Question: how to start the server without building first? 

### ISSUE THREAD

**Issue by ghost** [vladotesanovic/angular2-express-starter#84]
After the app has ben built once using "npm run build", I'd like to be able to launch the server without rebuilding.

I'd be super thankful if someone could help me here, I've tried many things without success.

**Comment by vladotesanovic** [comment]
If you are on Linux ( tested on Ubuntu ) you can use:

from project root:
```
export NODE_ENV=production && node ./dist/server/bin/www.js
```

**Comment by ghost** [comment]
Thanks!
