### ISSUE TITLE
Connect with differents hosts

### ISSUE THREAD

**Issue by tibs245** [vladotesanovic/angular2-express-starter#86]
Hello,
I would like to know how I could do in order to access the project from different hosts of the network to access it from a container.

Wish file to modify to desactivate http "localhost" security ?

Thank you in advance ! 

Example of `Dockerfile ':
```
FROM node:6.11.2

LABEL maintainer="tibs@kolombo.xyz"
LABEL version="1"

EXPOSE 8200
EXPOSE 8300

COPY ["./entrypoint.sh", "/"]

RUN chmod a+x "/entrypoint.sh"

WORKDIR /usr/lib/app
VOLUME /usr/lib/app

ENTRYPOINT ["/entrypoint.sh"]
CMD ["npm", "run", "start"]

```

And his entrypoint:

```
#!/usr/bin/env bash

cd /var/lib/app

npm install

exec "$@"

```

**Comment by ghost** [comment]
Hi,

I asked a related question a few months back: #57

You may find a hint in Vlado's answer. I never got it working with a proxy for the database though. Please let me know if you find a way.

**Comment by tibs245** [comment]
Yes ! I have found solution !
I have changed the run `ng serve` command in `package.json` with options : `-host 0.0.0.0 --disable-host-check`

Line 8 :
```
    "start": "concurrently --kill-others \"npm run _server:run\" \"ng serve --aot --host 0.0.0.0 --disable-host-check --progress=false --proxy-config proxy.conf.json\"",
 
```

**Comment by tibs245** [comment]
With your problem I think you miss just : `--disable-host-check`, Thank you !
