### ISSUE TITLE
Issues in Production

### ISSUE THREAD

**Issue by ghost** [vladotesanovic/angular2-express-starter#90]
I've looked through all of the closed issues and am still at a loss.

So I ran `npm run build` and then copied dist folder to the production server.

I try to run `node server/bin/www.js` and get the following error:

```
Error: Cannot find module 'body-parser'
```
What am I missing? does a package.json file also need to be copied and run via npm install?

**Comment by vladotesanovic** [comment]
Check this:
https://github.com/vladotesanovic/angular2-express-starter/issues/46#issuecomment-263519767

you need to deploy package.json as well, and to do 

```
npm install
```

**Comment by ghost** [comment]
I didn't notice it in #46 but that did get it to at least run (backend.) The frontend won't run because of a type error. Client side runs fine under `ng serve` (npm run start) but once I do `npm run build` it builds successfully but I get a console error of `TypeError: t[r] is undefined          main.1eda0feb0dddc7c4747b.bundle.js:1:791705` which is very nondescript. 

Any ideas as to how I can even start debugging this?

**Comment by kisonay** [comment]
turns out if you modify the build script to include --aot=false it is now successful. not really sure why but seems to be related to aot.

**Comment by yanbr01** [comment]
turns out there is an issue with Angular/cli... just so everyone know (if they run into a similar build issue.) https://github.com/angular/angular-cli/issues/9244#issuecomment-358605859

**Comment by kisonay** [comment]
turns out there is an issue with Angular/cli... just so everyone know (if they run into a similar build issue.) angular/angular-cli#9244 (comment)
