### ISSUE TITLE
NODE_DEBUG_OPTION not working

### ISSUE THREAD

**Issue by wertyoo** [vladotesanovic/angular2-express-starter#92]
Hi,

Love your setup. I am on windows 10 and using all the current versions of modules.

When I try to run the nodemon using the $NODE_DEBUG_OPTION, it fails with the error:
Cannot find module 'C:\Users[...]\angular2-express-starter\$NODE_DEBUG_OPTION'

Is this an issue with ts-node? or maybe the setup here?

**Comment by vladotesanovic** [comment]
hm,

$NODE_DEBUG_OPTION does not work with ts-node, and in combination with nodemon, it will be weird.

I spouse you want to debug server side.
What IDE are you using?

**Comment by wertyoo** [comment]
I am using WebStorm, though I am not sure if I have it setup correctly,
just using the default settings.

**Comment by vladotesanovic** [comment]
This is my configuration ( notice Before lunch script )

![image](https://user-images.githubusercontent.com/738638/37664452-adbb2eec-2c5b-11e8-87c0-cb3d107502c9.png)

Than i put break point in public.ts file, and open http://localhost:4300/api/public/simple

![image](https://user-images.githubusercontent.com/738638/37664646-00931080-2c5c-11e8-8f32-4ad43f0d3d43.png)

**Comment by wertyoo** [comment]
Ok, it is working now! Thank you very much!

**Comment by vladotesanovic** [comment]
np :)

**Comment by ianrussel** [comment]
What is exactly the error? I encountered this also
And how do you resolve this? I am using Atom Editor
